sudo: false
language: ruby
rvm:
  - jruby-19mode
  - jruby-9.0.0.0.pre1
jdk: openjdk7

cache:
  - bundler

matrix:
  allow_failures:
  - rvm: jruby-9.0.0.0.pre1
    jdk: openjdk7
  fast_finish: true

services:
  - redis

addons:
  postgresql: 9.3

before_script:
  - bundle exec rake db:create
script:
  - bundle exec rspec --require spec_helper
