sudo: false
language: ruby
rvm:
  - jruby-1.7.20
jdk: openjdk7

cache:
  - bundler

matrix:
  allow_failures:
  - rvm: jruby-head
    env: RAKE_TASK=spec
  fast_finish: true

services:
  - redis

addons:
  postgresql: 9.3

before_script:
  - bundle exec rake 'test:setup'
script:
  - bundle exec rspec --require spec_helper
