sudo: false
language: ruby

rvm:
  - 2.2
  - jruby-9.0.3.0

services:
  - redis
  - rabbitmq

addons:
  postgresql: 9.3

cache:
  - bundler

before_install:
  - which bundle || gem install bundler

before_script:
  - psql -q < spec/support/db.sql

script:
  - bundle exec rspec --require spec_helper
