sudo: false
language: ruby

rvm:
  - 2.2

services:
  - redis
  - rabbitmq

addons:
  postgresql: 9.3

cache:
  - bundler

before_install:
  - which bundle || gem install bundler

before_script:
  - sh "cp #{Gem.loaded_specs['travis-migrations'].full_gem_path}/db/structure.sql spec/support/db/structure.sql"
  - psql -q < spec/support/structure.sql

script:
  - bundle exec rspec --require spec_helper
