dist: trusty
sudo: false

rvm: 2.4.2

cache: bundler

env:
  global:
  - COVERAGE=1

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: 9.3

before_install:
  - bundle config https://gems.contribsys.com/ $BUNDLE_GEMS__CONTRIBSYS__COM

before_script:
  - bundle exec rake db:create --trace

script:
  - bundle exec rspec
