sudo: false
language: ruby

rvm:
  - 2.2

env:
  - TRAVIS_HUB_LOGS_API_ENABLED=1
  - TRAVIS_HUB_LOGS_API_ENABLED=0

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: 9.3

cache:
  - bundler

before_install:
  - bundle config https://gems.contribsys.com/ $BUNDLE_GEMS__CONTRIBSYS__COM

before_script:
  - bundle exec rake db:create --trace

script:
  - bundle exec rspec
